ARG DOCKER_TAG_BASE=openscad-base

FROM ${DOCKER_TAG_BASE}

ARG EMSCRIPTEN_FLAGS=""
ARG CMAKE_BUILD_TYPE=Release

ENV CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
ENV CMAKE_C_FLAGS="${EMSCRIPTEN_FLAGS}"
ENV CMAKE_CXX_FLAGS="${EMSCRIPTEN_FLAGS}"
ENV CMAKE_EXE_LINKER_FLAGS="${EMSCRIPTEN_FLAGS}"

COPY . . 
RUN emcmake cmake -B ../build . \
        -DBoost_USE_STATIC_RUNTIME=ON \
        -DBoost_USE_STATIC_LIBS=ON \
        -DEXPERIMENTAL=ON \
        -DSNAPSHOT=ON \
        -G Ninja && \
    cmake --build ../build --parallel
